name: Build

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    name: Deploy
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies & tooling
        run: |
          npm install
          npm run lint
