name: NPM Release

on:
  workflow_dispatch:  # Allow manual trigger
  push:
    branches:
      - main
    paths:
      - 'package.json'

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    name: Publish to NPM
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check version change
        if: github.event_name == 'push'  # Only run version check on push events
        id: check_version
        run: |
          PREV_VERSION=$(git show HEAD^:package.json | jq -r .version)
          CURRENT_VERSION=$(jq -r .version package.json)
          if [ "$PREV_VERSION" = "$CURRENT_VERSION" ]; then
            echo "No version change detected, skipping release"
            echo "version_changed=false" >> $GITHUB_OUTPUT
          else
            echo "Version changed from $PREV_VERSION to $CURRENT_VERSION"
            echo "version_changed=true" >> $GITHUB_OUTPUT
          fi

      - name: Setup Bun
        if: github.event_name != 'push' || steps.check_version.outputs.version_changed == 'true'
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        if: github.event_name != 'push' || steps.check_version.outputs.version_changed == 'true'
        run: bun install

      - name: Run lint
        if: github.event_name != 'push' || steps.check_version.outputs.version_changed == 'true'
        run: bun run lint

      - name: Release to NPM
        if: github.event_name != 'push' || steps.check_version.outputs.version_changed == 'true'
        run: bun run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
